version: "3.9"
services:
  mongo_db:
    image: mongo:latest
    container_name: uni-app-mongodb
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  server:
    build: ./server/
    volumes:
      - ./server/:/server/
    environment:
      PORT: 4000
      DATABASE_URL: mongodb://mongo_db:27017/university-list-app
    ports:
      - 4000:4000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
